POST http://localhost:8080/payment
Accept: application/json
Content-Type: application/json

{
  "firstname": "Fabrichio",
  "lastname": "Perez",
  "cardNumber": "46546546",
  "securityCode": "646",
  "dateExpire": "2008-11-11"
}