POST http://localhost:8080/payment
Accept: application/json
Content-Type: application/json

{
  "firstname": "Fabricio",
  "lastname": "Perez",
  "cardNumber": "1234",
  "securityCode": "22",
  "dateExpire": "2008-11-11"
}